name: DR2 Release Anonymiser Binary and docker image
on:
  push:
    branches:
      - main
      - DR2-1358-create-anonymiser-lambda
permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@main
        with:
          repo-name: dr2-court-document-package-anonymiser
      - run: |
          cargo build --release
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
          gh release create ${{ steps.next-tag.outputs.next-version }} target/release/anonymiser
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT_NUMBER }}:role/MgmtDPGithubImageDeploy
          aws-region: us-east-1
          role-session-name: ECRLogin
      - uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
      - run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl
          docker build -t public.ecr.aws/u4s1g5v1/anonymiser .
          docker push public.ecr.aws/u4s1g5v1/anonymiser
  documentation-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
      - run:
          cargo doc --no-deps --workspace --document-private-items
          git config --global user.email digitalpreservation@nationalarchives.gov.uk
          git config --global user.name tna-digital-archiving-jenkins
          git checkout gh-pages
          rm -rf docs
          mv target/doc/ docs
          git add docs
          git commit -m "Update site documentation"
          git push -u origin gh-pages


