name: DR2 Release Anonymiser Binary and docker image
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - id: next-tag
        uses: nationalarchives/dr2-github-actions/.github/actions/get-next-version@917201e254f112ff041b952dae76ef767cae7378
        with:
          repo-name: dr2-court-document-package-anonymiser
      - run: |
          cargo build --release -p anonymiser
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
          gh release create ${{ steps.next-tag.outputs.next-version }} target/release/anonymiser
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@6e562ac9abb118b648a1c7765070c66a1c996eb6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT_NUMBER }}:role/MgmtDPGithubImageDeploy
          aws-region: us-east-1
          role-session-name: ECRLogin
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: public.ecr.aws
      - run: |
          sudo apt-get install musl-tools
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl
          docker build -t public.ecr.aws/u4s1g5v1/anonymiser .
          docker push public.ecr.aws/u4s1g5v1/anonymiser
  documentation-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          fetch-depth: '0'
      - run:  |
          cargo doc --no-deps --workspace --document-private-items
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com 
          git config --global user.name tna-da-bot
          git checkout gh-pages
          rm -rf docs
          mv target/doc/ docs
          git add docs
          git commit -m "Update site documentation"
          git push -u origin gh-pages
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - run: gh workflow run deploy_lambda.yml
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
