name: DR2 Run Tests
on:
  push:
    branches-ignore:
      - main
      - release-*
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: nationalarchives/dr2-github-actions/.github/workflows/dr2_test.yml@main
    with:
      repo-name: dr2-court-document-package-anonymiser
      test-command: |
        cargo fmt --check
        cargo test --workspace
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
